image:
  # - Visual Studio 2019
  - Ubuntu
  - macOS

environment:
  matrix:

  - TOXENV: py36    # https://devguide.python.org/#status-of-python-branches
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310

matrix:
  fast_finish: true

stack: python 3

install:
  - cmd: py -m pip install --upgrade pip
  - cmd: py -m pip install tox
  - sh: sudo apt-get install python3-dev
  - sh: python3 -m pip install --upgrade pip
  - sh: python3 -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - cmd: py -m tox
  - sh: python3 -m tox

# after_test:
  # # If tests are successful, create a whl package for the project.
  # - python setup.py bdist_wheel
  # - ps: "ls dist"
# 
# artifacts:
  # # Archive the generated wheel package in the ci.appveyor.com build report.
  # - path: dist/*.whl
# 
# version: v14.0.0-b{build}
# 
# deploy:
  # # Deploy wheels on tags to GitHub Releases
  # - provider: GitHub
    # tag: v14.0.0
    # release: v14.0.0
    # auth_token:
      # secure: /EpkTwEg8UAGemXkhpKbelv/FZ5fud9AjCHsnt5SiuBkxCfm8sJRzWPbMpvd+YOE
    # draft: false
    # prerelease: false
    # on:
      # branch: master
