name: Tests
on: [push]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ARCHS: ${{ matrix.arch }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [all]
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
