name: Tests
on: [push]
jobs:
  test_and_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [auto64, aarch64]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', pypy-3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions cibuildwheel
    - name: Test with tox
      run: tox
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - uses: action/upload-artifact@v2
      with:
        name: unicodedataplus-${{ matrix.os }}-${{ matrix.arch }}
        path: wheelhouse/*.whl
