name: Tests
on: [push]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ARCHS: ${{ matrix.arch }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [auto]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_SKIP: cp36-* cp37-* cp313-* pp37-* pp38-*
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  deploy:
    if: github.ref_type == 'tag'
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Download artifacts from build jobs
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse/
      - name: Move wheels to dist/ directory
        run: |
          mkdir -p dist/
          find . -type f -name "unicodedataplus*.whl" -exec mv {} dist/ \;
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload dist/*
